name: 🐛 Bug Report
description: Report a bug or unexpected behavior in HL7 Forge
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out as much detail as possible.

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which part of HL7 Forge is affected?
      options:
        - MLLP Server (TCP listener, framing, ACK/NACK)
        - HL7 Parser (message parsing, delimiter detection)
        - Web UI (browser SPA, display, interaction)
        - WebSocket (real-time updates, connection)
        - REST API (/api/messages, /api/search, /api/stats)
        - Message Store (in-memory store, eviction)
        - Build / CI / Deployment
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: When I send an ADT^A01 message with special characters in PID-5, the parser fails to...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this behavior?
      placeholder: |
        1. Start hl7-forge with default settings
        2. Send this HL7 message via netcat: ...
        3. Open Web UI at http://localhost:8080
        4. Click on the message
        5. See error in ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened? Include error messages, logs, or screenshots if available.
    validations:
      required: true

  - type: textarea
    id: hl7-sample
    attributes:
      label: HL7 Message Sample
      description: If applicable, provide a (de-identified!) sample HL7 message that triggers the bug.
      render: text
      placeholder: |
        MSH|^~\&|SENDING|FACILITY|HL7FORGE|HL7FORGE|20240101120000||ADT^A01|MSG001|P|2.5
        PID|||12345||Doe^John||19900101|M
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - Linux
        - macOS
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: HL7 Forge Version
      description: Release version or commit hash
      placeholder: "v0.1.0 or commit abc1234"
    validations:
      required: true

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Method
      options:
        - cargo run (from source)
        - Pre-built binary (.exe / release)
        - Windows Service (NSSM)
        - Docker (if applicable)
        - Other
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Anything else? Logs, environment details, port configuration, browser used for Web UI, etc.
    validations:
      required: false
